name: CI

on:
  push:
    branches: "**"

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
          cache-dependency-path: package-lock.json
      - run: npm ci
      - run: npm run lint
      - run: npm run test
        env:
          NODE_OPTIONS: --max-old-space-size=4096
          NO_COLOR: true
